apiVersion: v1
kind: Service
metadata:
  name: my-sample-app-service
  namespace: default
  labels:
    app: my-sample-app
spec:
  type: ClusterIP
  selector:
    app: my-sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080