apiVersion: v1
kind: Service
metadata:
  name: my-sample-app-service
  labels:
    app: my-sample-app
spec:
  type: ClusterIP
  selector:
    app: my-sample-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000